"""
Generated by Claude on April 20, 2026 | Prompted by Suppakorn (Tae)
--------------------
Reads a CSV with columns:
    filename, caption, predicted_caption

Computes:
    1. BLEU-1 to BLEU-4   (corpus-level, NLTK)
    2. BERTScore           (Precision / Recall / F1, microsoft/deberta-xlarge-mnli)
    3. CIDEr               (standard image-captioning benchmark, TF-IDF n-gram weighting)

Usage:
    python evaluate_captions.py --csv path/to/results.csv [--device cpu]

The script also saves a per-image score breakdown to:
    <csv_stem>_scores.csv
"""

import argparse
import csv
import os
import sys

import torch
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction
from bert_score import score as bert_score_fn
from pycocoevalcap.cider.cider import Cider


# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────

def load_csv(path: str):
    """Return (filenames, references, hypotheses) lists from the CSV."""
    if not os.path.exists(path):
        sys.exit(f"[ERROR] CSV not found: {path}")

    filenames, refs, hyps = [], [], []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        required = {"filename", "caption", "predicted_caption"}
        if not required.issubset(reader.fieldnames or []):
            sys.exit(
                f"[ERROR] CSV must have columns: {required}\n"
                f"       Found: {reader.fieldnames}"
            )
        for row in reader:
            filenames.append(row["filename"])
            refs.append(row["caption"].strip())
            hyps.append(row["predicted_caption"].strip())

    print(f"[INFO] Loaded {len(refs)} rows from '{path}'")
    return filenames, refs, hyps


# ─────────────────────────────────────────────
# BLEU
# ─────────────────────────────────────────────

def compute_bleu(references: list[str], hypotheses: list[str]) -> dict:
    refs_tok = [[r.lower().split()] for r in references]
    hyps_tok = [h.lower().split() for h in hypotheses]
    smoother = SmoothingFunction().method1

    scores = {}
    for n, weights in [
        (1, (1.0, 0.0, 0.0, 0.0)),
        (2, (0.5, 0.5, 0.0, 0.0)),
        (3, (1/3, 1/3, 1/3, 0.0)),
        (4, (0.25, 0.25, 0.25, 0.25)),
    ]:
        scores[f"bleu_{n}"] = corpus_bleu(
            refs_tok, hyps_tok, weights=weights, smoothing_function=smoother
        ) * 100

    return scores


# ─────────────────────────────────────────────
# BERTScore
# ─────────────────────────────────────────────

def compute_bertscore(references: list[str], hypotheses: list[str], device: str):
    """Returns per-sentence P/R/F1 tensors and corpus averages."""
    print("[INFO] Computing BERTScore (this may take a moment on first run)...")
    P, R, F1 = bert_score_fn(
        hypotheses,
        references,
        lang="en",
        device=device,
        verbose=False,
    )
    return (
        P.tolist(), R.tolist(), F1.tolist(),
        P.mean().item() * 100,
        R.mean().item() * 100,
        F1.mean().item() * 100,
    )


# ─────────────────────────────────────────────
# CIDEr
# ─────────────────────────────────────────────

def compute_cider(filenames: list[str], references: list[str], hypotheses: list[str]):
    """
    Uses pycocoevalcap's Cider scorer.
    gts / res dicts: { image_id: [str] }  — plain strings, NOT dicts.
    """
    gts = {fname: [ref] for fname, ref in zip(filenames, references)}
    res = {fname: [hyp] for fname, hyp in zip(filenames, hypotheses)}

    scorer = Cider()
    corpus_score, per_image_scores = scorer.compute_score(gts, res)
    return corpus_score * 100, per_image_scores  # scale to 0-100


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Evaluate image captioning metrics from CSV.")
    parser.add_argument("--csv", required=True, help="Path to results CSV.")
    parser.add_argument(
        "--device",
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="Device for BERTScore (default: auto).",
    )
    args = parser.parse_args()

    filenames, references, hypotheses = load_csv(args.csv)

    # ── 1. BLEU ──────────────────────────────────────────────────────────────
    print("\n[INFO] Computing BLEU scores...")
    bleu = compute_bleu(references, hypotheses)

    # ── 2. BERTScore ─────────────────────────────────────────────────────────
    P_list, R_list, F1_list, bert_P, bert_R, bert_F1 = compute_bertscore(
        references, hypotheses, args.device
    )

    # ── 3. CIDEr ─────────────────────────────────────────────────────────────
    print("[INFO] Computing CIDEr scores...")
    cider_corpus, cider_per_image = compute_cider(filenames, references, hypotheses)

    # ── Print Summary ─────────────────────────────────────────────────────────
    sep = "=" * 55
    print(f"\n{sep}")
    print("  EVALUATION SUMMARY")
    print(sep)

    print("\n  ── BLEU Scores (corpus-level) ──")
    print(f"    BLEU-1 : {bleu['bleu_1']:6.2f}")
    print(f"    BLEU-2 : {bleu['bleu_2']:6.2f}")
    print(f"    BLEU-3 : {bleu['bleu_3']:6.2f}")
    print(f"    BLEU-4 : {bleu['bleu_4']:6.2f}")

    print("\n  ── BERTScore (corpus average, %) ──")
    print(f"    Precision : {bert_P:6.2f}")
    print(f"    Recall    : {bert_R:6.2f}")
    print(f"    F1        : {bert_F1:6.2f}")

    print("\n  ── CIDEr Score ──")
    print(f"    CIDEr (×100) : {cider_corpus:6.2f}")

    print(f"\n{sep}\n")

    # ── Save per-image breakdown ──────────────────────────────────────────────
    stem = os.path.splitext(args.csv)[0]
    out_path = f"{stem}_scores.csv"

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "filename", "caption", "predicted_caption",
            "bert_P", "bert_R", "bert_F1", "cider"
        ])
        for i, fname in enumerate(filenames):
            cider_val = (
                cider_per_image[i] * 100
                if hasattr(cider_per_image, "__len__")
                else cider_corpus
            )
            writer.writerow([
                fname,
                references[i],
                hypotheses[i],
                f"{P_list[i]*100:.4f}",
                f"{R_list[i]*100:.4f}",
                f"{F1_list[i]*100:.4f}",
                f"{cider_val:.4f}",
            ])

    print(f"[INFO] Per-image scores saved to: {out_path}")


if __name__ == "__main__":
    main()